export function generateDoctorReportPdf(form, fresshTotal) {
    const doc = new jsPDF();

    // --- Local Layout ---
    const M = 10;
    const PW = 210;
    const PH = 297;
    const UW = PW - M * 2;
    const gap = 4;
    const cardW = (UW - gap) / 2;
    let cy = M;

    // --- Local Colors ---
    const C_BG = [239, 246, 255];       // #EFF6FF very soft blue
    const C_CYAN = [224, 242, 254];     // #E0F2FE soft cyan
    const C_BORDER = [191, 219, 254];   // #BFDBFE blue border
    const C_TEXT = [15, 23, 42];        // #0F172A slate-900
    const C_MUTED = [100, 116, 139];    // #64748B slate-500
    const C_ACCENT = [37, 99, 235];     // #2563EB accent blue
    const C_WHITE = [255, 255, 255];
    const C_RED = [220, 38, 38];        // red for flags
    const C_GREEN = [5, 150, 105];      // green for OK

    // --- Data Extraction ---
    const p = form.patient || {};
    const b = form.birth || {};
    const peri = form.perinatal || {};
    const h = form.history || {};
    const t = form.time || {};
    const med = form.medical || {};
    const diagRaw = form.diagnosis || {};
    const exam = form.examination || {};
    const dev = form.development || {};
    const final_ = form.final || {};
    const impact = form.impact || {};
    const yesterday = form.yesterday || {};
    const diagSummary = getSuggestedDiagnosisSummary(form);
    const redFlags = getRedFlagSummary(form);
    const familyRows = form.familyRows || [];

    // --- Local Helpers ---
    const clean = (val) => {
        if (val === undefined || val === null) return "ΓÇö";
        let s = String(val).trim();
        if (!s || s.toLowerCase() === "undefined" || s.toLowerCase() === "not provided") return "ΓÇö";
        // Strip boilerplate and autogenerated jargon
        const junk = [
            "Doctor must confirm", "Clinician confirmation required",
            "Generated from Beat Headache form responses", "Generated from Beat Headache form",
            "clinical/research review support only", "Not a diagnosis",
            "See full clinical record for complete details.", "See full clinical record.",
            "See full clinical record", "Previous diagnosis reported", "Referral source",
            "Headache impact reported", "Duration: undefined", "Severity: undefined",
            "Suggested diagnosis status from Page 5", "Doctor should review"
        ];
        junk.forEach(j => { s = s.replace(new RegExp(j, "gi"), ""); });
        s = s.replace(/\s{2,}/g, " ").trim();
        if (s.endsWith(":") || s.endsWith(",")) s = s.slice(0, -1).trim();
        return s || "ΓÇö";
    };

    const pickFinalProgressiveValue = (items) => {
        if (!items || items.length === 0) return [];
        // Sort by length descending to find longest versions first
        const sorted = items.map(String).filter(x => x && x !== "ΓÇö").sort((a, b) => b.length - a.length);
        const finals = [];
        sorted.forEach(item => {
            if (!finals.some(f => f.includes(item))) {
                finals.push(item);
            }
        });
        return finals;
    };

    const cleanArr = (arr, max = 6) => {
        let items = Array.isArray(arr) ? arr.filter(Boolean).map(clean).filter(x => x !== "ΓÇö") : [];
        if (items.length === 0) return "None";
        items = pickFinalProgressiveValue(items);
        const unique = [...new Set(items)];
        if (unique.length <= max) return unique.join(", ");
        return unique.slice(0, max).join(", ") + " ...";
    };

    const dedupeText = (text) => {
        if (!text) return "ΓÇö";
        const lines = String(text).split(/\n+|\s*\|\s*/).map(l => l.trim()).filter(Boolean);
        const items = pickFinalProgressiveValue(lines).map(clean).filter(x => x !== "ΓÇö");
        const unique = [...new Set(items)];
        return unique.length > 0 ? unique.join("; ") : "ΓÇö";
    };

    const trunc = (text, maxLen = 80) => {
        const s = clean(text);
        if (s === "ΓÇö") return s;
        return s.length <= maxLen ? s : s.slice(0, maxLen - 3) + "...";
    };

    const parseParity = (val) => {
        const s = String(val || "").trim();
        if (!s || s === "Not provided" || s === "ΓÇö") return { p: "ΓÇö", c: "ΓÇö" };
        const pM = s.match(/P\s*[:\[\s]*(\d+)/i);
        const cM = s.match(/C\s*[:\[\s]*(\d+)/i);
        let pv = pM ? pM[1] : "";
        let cv = cM ? cM[1] : "";
        if (!pv && !cv && /^\d+$/.test(s)) pv = s;
        return { p: pv || "ΓÇö", c: cv || "ΓÇö" };
    };

    const safeDay = (val) => {
        const n = parseInt(val);
        if (isNaN(n) || n < 0) return "Not recorded";
        return `${n} d`;
    };

    // Filter out auto-generated jargon from secondary notes
    const cleanSecondaryNotes = (text) => {
        if (!text) return "";
        const jargon = [
            "suggested because", "previous diagnosis", "previous treatment",
            "referral source", "developmental concern", "developmental history concern",
            "prodromal symptoms", "aura symptoms", "suggested review", "postdrome reported",
            "chronic headache history", "doctor review note", "medicine used for headache",
            "frequent medicine use", "severity score from page", "migraine-supporting",
            "lifestyle note", "previous response:", "premonitory symptoms",
            "headache impact reported", "headache reported yesterday", "medicine taken yesterday",
            "suggested check", "medication safety warning", "red flag selected",
            "clinical/research review", "clinician confirmation", "not a diagnosis",
            "doctor must", "clinician must", "see full clinical",
            "possible non-primary", "possible ent-related", "possible secondary",
            "possible tm joint-related", "check current/past", "medication safety"
        ];
        const lines = String(text).split(/\n+|\s*\|\s*/).map(l => l.trim()).filter(Boolean)
            .filter(line => !jargon.some(j => line.toLowerCase().includes(j)));
        return lines.join(", ");
    };

    // --- Page-break aware Y tracker (DISABLED for one-page) ---
    const ensureSpace = (need) => {
        // No page breaks allowed for one-page report
        return false;
    };

    // --- Drawing Helpers ---
    const drawHeader = () => {
        doc.setFillColor(...C_BG);
        doc.rect(0, 0, PW, 18, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(...C_TEXT);
        doc.text("Beat Headache", M, 10);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8.5);
        doc.setTextColor(...C_MUTED);
        doc.text("Doctor Clinical Report", M, 14);
        const codeStr = p.registrationCode ? `ID: ${p.registrationCode}` : "";
        const rightInfo = [codeStr, `Date: ${new Date().toLocaleDateString()}`].filter(Boolean).join(" | ");
        doc.setFontSize(8);
        doc.text(rightInfo, PW - M, 14, { align: "right" });
        cy = 22;
    };

    const drawSectionTitle = (title) => {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.5);
        doc.setTextColor(...C_ACCENT);
        doc.text(title.toUpperCase(), M, cy);
        cy += 2.5;
    };

    const drawFieldBox = (label, value, bx, by, bw, bh) => {
        doc.setFillColor(...C_WHITE);
        doc.setDrawColor(...C_BORDER);
        doc.setLineWidth(0.2);
        doc.roundedRect(bx, by, bw, bh, 1, 1, "FD");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(6);
        doc.setTextColor(...C_MUTED);
        doc.text(label, bx + 1.5, by + 3);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7);
        doc.setTextColor(...C_TEXT);
        doc.text(trunc(value, bw / 1.3), bx + 1.5, by + 7);
    };

    const drawInlineField = (label, value, fx, fy, labelW) => {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(6);
        doc.setTextColor(...C_MUTED);
        doc.text(label, fx, fy);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(6.5);
        doc.setTextColor(...C_TEXT);
        doc.text(trunc(value, 50), fx + (labelW || 22), fy);
    };

    const drawCard = (cx, cy_, cw, title, rows) => {
        const rowH = 3.8;
        const ch = 5 + rows.length * rowH + 1;
        doc.setDrawColor(...C_BORDER);
        doc.setFillColor(...C_WHITE);
        doc.roundedRect(cx, cy_, cw, ch, 1, 1, "FD");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(6.5);
        doc.setTextColor(...C_ACCENT);
        doc.text(title.toUpperCase(), cx + 2, cy_ + 4);
        let ly = cy_ + 8;
        rows.forEach(r => {
            doc.setFont("helvetica", "bold");
            doc.setFontSize(6);
            doc.setTextColor(...C_MUTED);
            doc.text(r[0], cx + 2, ly);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(...C_TEXT);
            const val = clean(r[1]);
            const lines = doc.splitTextToSize(val, cw - 25);
            doc.text(lines[0] || "ΓÇö", cx + 22, ly);
            ly += rowH;
        });
        return ch;
    };

    const drawFeatureBlock = (label, value, fx, fy, fw, fh) => {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(6);
        doc.setTextColor(...C_MUTED);
        doc.text(label, fx, fy);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(6.5);
        doc.setTextColor(...C_TEXT);
        const val = clean(value);
        const lines = doc.splitTextToSize(val, fw);
        const maxLines = Math.floor((fh || 5) / 2.8);
        doc.text(lines.slice(0, maxLines), fx, fy + 2.8);
    };

    // ============================================================
    //  DOCTOR REPORT CONTENT (ONE PAGE)
    // ============================================================
    drawHeader();

    // --- Top Demographics ---
    const bw = (UW - 4) / 3;
    drawFieldBox("Patient ID", p.registrationCode || "N/A", M, cy, bw, 9);
    drawFieldBox("Age / Gender", `${clean(p.age)} / ${clean(p.gender)}`, M + bw + 2, cy, bw, 9);
    drawFieldBox("Ethnicity", clean(p.ethnicity), M + bw * 2 + 4, cy, bw, 9);
    cy += 11;

    const prevDiag = dedupeText(form.clinicPath?.previousDiagnosis);
    drawFieldBox("Referral", clean(form.referral?.source), M, cy, bw, 9);
    drawFieldBox("Visit Type", clean(form.clinicPath?.initiatedBy), M + bw + 2, cy, bw, 9);
    drawFieldBox("Previous Diagnosis", prevDiag, M + bw * 2 + 4, cy, bw, 9);
    cy += 12;

    // --- Assessment & Plan (Compact) ---
    drawSectionTitle("Assessment & Plan");
    doc.setFillColor(...C_CYAN);
    doc.roundedRect(M, cy, UW, 12, 1, 1, "F");
    doc.setFont("helvetica", "bold"); doc.setFontSize(6.5); doc.setTextColor(...C_ACCENT);
    doc.text("Working Impression:", M + 2, cy + 4);
    doc.setFont("helvetica", "bold"); doc.setFontSize(7); doc.setTextColor(...C_TEXT);
    const impTxt = clean(diagSummary.likelyType) + " ΓÇö " + clean(diagSummary.explanation);
    const impLines = doc.splitTextToSize(impTxt, UW - 38);
    doc.text(impLines.slice(0, 2), M + 36, cy + 4);
    cy += 14;

    doc.setFont("helvetica", "normal"); doc.setFontSize(6.5); doc.setTextColor(...C_TEXT);
    if (form.clinicPath?.previousTreatmentOutcome) {
        doc.setFont("helvetica", "bold"); doc.text("Prev. Treatment:", M, cy);
        doc.setFont("helvetica", "normal"); doc.text(trunc(form.clinicPath.previousTreatmentOutcome, 150), M + 22, cy);
        cy += 3.5;
    }
    
    const medicineNote = `Used in last 4 weeks; yesterday: ${clean(yesterday.hadHeadacheYesterday === "Yes" ? "taken" : "none")}`;
    doc.setFont("helvetica", "bold"); doc.text("Medicine Use:", M, cy);
    doc.setFont("helvetica", "normal"); doc.text(medicineNote, M + 22, cy);
    cy += 3.5;

    if (med.allergies === "Yes" && med.allergySpecify) {
        doc.setFont("helvetica", "bold"); doc.setTextColor(...C_RED);
        doc.text("Safety Notes:", M, cy);
        doc.setFont("helvetica", "normal"); doc.text(`Allergy: ${trunc(med.allergySpecify, 140)}`, M + 22, cy);
        cy += 3.5;
    }

    if (exam.tests) {
        doc.setFont("helvetica", "bold"); doc.setTextColor(...C_ACCENT);
        doc.text("Suggested Tests:", M, cy);
        doc.setFont("helvetica", "normal"); doc.setTextColor(...C_TEXT);
        doc.text(trunc(exam.tests, 140), M + 22, cy);
        cy += 4;
    }
    cy += 2;

    // --- Background Summary ---
    drawSectionTitle("Background Summary");
    const parityObj = parseParity(b.parity);
    let pVal = peri.pregnancyNumber || parityObj.p;
    let cVal = peri.childNumber || parityObj.c;
    const mother = familyRows[0] || {};
    const father = familyRows[1] || {};
    const siblings = familyRows.slice(2).filter(s => s && s.age);
    const sibDetails = siblings.map(s => `${s.relation || "Sib"} ${s.age}y`).join(", ") || "None";

    drawInlineField("Pregnancy/Parity", `P [${pVal}]  C [${cVal}]`, M, cy, 22);
    drawInlineField("Mother", trunc(`${mother.age || "?"}y, ${mother.issues?.length ? mother.issues.join(",") : "None"}`, 45), M + UW / 2, cy, 12);
    cy += 3.5;
    drawInlineField("Gestation", `${clean(b.gestation)} wks`, M, cy, 22);
    drawInlineField("Father", trunc(`${father.age || "?"}y, ${father.issues?.length ? father.issues.join(",") : "None"}`, 45), M + UW / 2, cy, 12);
    cy += 3.5;
    drawInlineField("Birth / Consanguinity", `${clean(b.birthWeight)} kg / ${clean(b.delivery)} | Consang: ${clean(b.consanguinity)}`, M, cy, 28);
    drawInlineField("Siblings", trunc(sibDetails, 45), M + UW / 2, cy, 12);
    cy += 5;

    // Perinatal & Medical Card
    doc.setFillColor(...C_CYAN);
    doc.roundedRect(M, cy, UW, 14, 1, 1, "F");
    doc.setFont("helvetica", "bold"); doc.setFontSize(6); doc.setTextColor(...C_ACCENT);
    doc.text("Perinatal & Medical History:", M + 2, cy + 3.5);
    doc.setFont("helvetica", "normal"); doc.setFontSize(6.5); doc.setTextColor(...C_TEXT);
    doc.text(trunc(`Perinatal: ${clean(peri.complications)} | PBU: ${peri.pbuStay === "Y" ? (peri.pbuDays + " d") : "No"} | ${clean(peri.other)}`, 140), M + 32, cy + 3.5);
    doc.text(trunc(`Medical: ${clean(med.pastMedical)} | Surgical: ${clean(med.pastSurgical)} | Drugs: ${clean(med.drugHistory)}`, 160), M + 2, cy + 7.5);
    doc.text(trunc(`Allergies: ${med.allergies === "Yes" ? clean(med.allergySpecify) : "None"}`, 160), M + 2, cy + 11.5);
    cy += 17;

    // --- Development & Impact (Compact) ---
    const ch2 = drawCard(M, cy, UW, "Development & Impact", [
        ["Motor/Speech", `Gross: ${dev.grossMotorIssue === "Yes" ? clean(dev.grossMotorDescribe) : "Normal"} | Fine: ${dev.fineMotorIssue === "Yes" ? clean(dev.fineMotorDescribe) : "Normal"} | Speech: ${dev.speechIssue === "Yes" ? clean(dev.speechDescribe) : "Normal"}`],
        ["School/Activity", `Absence: ${clean(impact.schoolAbsentDaysLastFourWeeks)}d/4wks | Activity Limited: ${clean(impact.activityLimitedDaysLastFourWeeks)}d/4wks`],
        ["Parent/Yday", `Work Loss: ${clean(impact.parentLostWork)} (${clean(impact.parentLostWorkDays)}d) | Yesterday HA: ${clean(yesterday.hadHeadacheYesterday)} (${clean(yesterday.severity)})`]
    ]);
    cy += ch2 + 4;

    // --- Headache Phenotype ---
    drawSectionTitle("Headache Phenotype");
    const hCardH = 28;
    doc.setDrawColor(...C_BORDER); doc.setFillColor(...C_WHITE);
    doc.roundedRect(M, cy, UW, hCardH, 1, 1, "FD");
    const colW_ = (UW - 4) / 2;
    drawFeatureBlock("HISTORY & PATTERN", `${h.durationYears || 0}y ${h.durationMonths || 0}m | ${clean(h.pattern)}`, M + 2, cy + 4, colW_ - 4, 5);
    drawFeatureBlock("LOCATION & SIDE", cleanArr(h.location, 3) + (h.frontalSide ? ` (F: ${h.frontalSide})` : "") + (h.temporalSide ? ` (T: ${h.temporalSide})` : ""), M + 2, cy + 11, colW_ - 4, 5);
    drawFeatureBlock("PAIN CHARACTER", cleanArr(h.painNature, 3) + " | " + cleanArr(h.associated, 4), M + 2, cy + 18, colW_ - 4, 5);
    drawFeatureBlock("SEVERITY & DURATION", `${clean(t.headache?.severity)} | ${clean(t.headache?.duration)}`, M + colW_ + 2, cy + 4, colW_ - 4, 5);
    drawFeatureBlock("FREQUENCY", `${h.headacheDaysLastFourWeeks || 0} d/4wks | Meds: ${safeDay(h.medicineDaysLastFourWeeks)}`, M + colW_ + 2, cy + 11, colW_ - 4, 5);
    drawFeatureBlock("AURA & PROD/POST", `Aura: ${t.aura?.hasAura === "Yes" ? "Yes" : "No"} | Prod: ${t.prodromal?.hasProdromal === "Yes" ? "Yes" : "No"} | Post: ${t.postdrome?.hasPostdrome === "Yes" ? "Yes" : "No"}`, M + colW_ + 2, cy + 18, colW_ - 4, 5);
    drawFeatureBlock("TRIGGERS & RELIEF", `Trig: ${cleanArr(h.aggravating, 3)} | Rel: ${cleanArr(h.relief, 3)}`, M + 2, cy + 25, UW - 4, 5);
    cy += hCardH + 4;

    // --- Impression & Red Flags ---
    const rfCardH_ = 32;
    doc.setDrawColor(...C_BORDER); doc.setFillColor(...C_WHITE);
    doc.roundedRect(M, cy, cardW, rfCardH_, 1, 1, "FD");
    doc.setFont("helvetica", "bold"); doc.setFontSize(6.5); doc.setTextColor(...C_ACCENT);
    doc.text("PRIMARY IMPRESSION", M + 2, cy + 4);
    const primItems = [
        ["Migraine (No Aura)", clean(diagRaw["migraineNoAura.status"])],
        ["Migraine (With Aura)", clean(diagRaw["migraineAura.status"])],
        ["Tension-Type HA", clean(diagRaw["tension.status"])],
        ["Cluster HA", clean(diagRaw["cluster.status"])]
    ];
    let pY = cy + 8;
    primItems.forEach(item => {
        doc.setFont("helvetica", "bold"); doc.setFontSize(5.5); doc.setTextColor(...C_MUTED);
        doc.text(item[0], M + 2, pY);
        doc.setFont("helvetica", "normal"); doc.setTextColor(...C_TEXT);
        doc.text(item[1], M + 35, pY);
        pY += 3;
    });
    const uFeatures = [...new Set([...(diagRaw.migraineNoAuraCharacteristics || []), ...(diagRaw.tensionCharacteristics || []), ...(diagRaw.clusterSymptoms || [])])].map(clean).filter(x => x !== "ΓÇö");
    if (uFeatures.length > 0) {
        doc.setFont("helvetica", "bold"); doc.setFontSize(5.5); doc.setTextColor(...C_MUTED);
        doc.text("Features:", M + 2, pY + 1);
        doc.setFont("helvetica", "normal"); doc.setTextColor(...C_TEXT);
        const fLines = doc.splitTextToSize(uFeatures.join(", "), cardW - 14);
        doc.text(fLines.slice(0, 2), M + 12, pY + 1);
    }

    doc.setFillColor(...C_WHITE); // FIX: Ensure white fill before drawing the next card
    doc.roundedRect(M + cardW + 4, cy, cardW, rfCardH_, 1, 1, "FD");
    const rfC = redFlags.length;
    doc.setFont("helvetica", "bold"); doc.setFontSize(6.5);
    doc.setTextColor(...(rfC > 0 ? C_RED : C_ACCENT));
    doc.text(rfC > 0 ? "RED FLAGS DETECTED" : "RED FLAGS & SCREENING", M + cardW + 6, cy + 4);
    doc.setFont("helvetica", "normal"); doc.setFontSize(6);
    if (rfC > 0) {
        doc.setTextColor(...C_RED);
        const rLines = doc.splitTextToSize(cleanArr(redFlags, 10), cardW - 10);
        doc.text(rLines.slice(0, 2), M + cardW + 6, cy + 7.5);
    } else {
        doc.setTextColor(...C_MUTED);
        doc.text("None reported", M + cardW + 6, cy + 7.5);
    }
    const hasInf = redFlags.includes("Fever, acute symptoms") || exam.Gait === "Neck stiffness";
    const hasICP_ = redFlags.includes("Onset in sleep/early morning") || exam.Papilloedema === "Yes";
    const sItems = [
        ["Infection/ICP", `${hasInf ? "Yes" : "No"}/${hasICP_ ? "Yes" : "No"}`],
        ["ENT / Eye", `${(exam["Tenderness over Sinus"] === "Yes" || exam["Tenderness over Sinus"] === "AN") ? "Abn" : "Normal"} / ${(exam["Eye Movement"] === "Yes" || exam["Eye Movement"] === "AN") ? "Abn" : "Normal"}`],
        ["Med Overuse", (parseInt(h.medicineDaysLastFourWeeks) > 10) ? "Risk" : "Normal"]
    ];
    let sY = cy + 16;
    sItems.forEach(row => {
        doc.setFont("helvetica", "bold"); doc.setTextColor(...C_MUTED);
        doc.text(row[0], M + cardW + 6, sY);
        doc.setFont("helvetica", "normal"); doc.setTextColor(...C_TEXT);
        doc.text(row[1], M + cardW + 35, sY);
        sY += 3.2;
    });
    cy += rfCardH_ + 4;

    // --- Examination & Investigation ---
    drawSectionTitle("Examination & Investigation");
    const exH = drawCard(M, cy, UW, "Examination Findings", [
        ["Vitals/Growth", `Ht: ${clean(exam.height)}cm, Wt: ${clean(exam.weight)}kg, BMI: ${clean(exam.bmi)}, OFC: ${clean(exam.ofc)}cm`],
        ["BP / HR / Neuro", `${clean(exam.bpSystolic)}/${clean(exam.bpDiastolic)} | HR: ${clean(exam.heartRate)} | Papilloedema: ${clean(exam.Papilloedema)} | CN Palsy: ${clean(exam.crNvPalsy)}`],
        ["Gait / Eye / ENT", `Gait: ${clean(exam.Gait)} | Eye: ${clean(exam["Eye Movement"])} | Sinus: ${clean(exam["Tenderness over Sinus"])} | Teeth: ${clean(exam.Teeth)}`]
    ]);
    cy += exH + 2;

    doc.save(`BeatHeadache-Doctor-Clinical-Report-${p.registrationCode || "Report"}.pdf`);
}

